    //Try Catch: مدیریت خطا

try {
    let num1 = 5;
    let result;
    result = num1 = 10;
    console.log(sum);
    
} catch(error) {
    // console.log("دوباره سعی نمایید!!!");
    //console.log(error);
    //console.log(error.name);
    //console.log(error.message);
    console.log(`${error.name}: Please Declare sum First`);
}
    console.log("Mohammad");